# This file was generated by GoReleaser. DO NOT EDIT.
cask "voxclip" do
  name "voxclip"
  desc "Voice capture and transcription CLI — record, transcribe, and copy to clipboard locally"
  homepage "https://github.com/fmueller/voxclip"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "voxclip"
  depends_on formula: [
      "ffmpeg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fmueller/voxclip/releases/download/v#{version}/voxclip_#{version}_darwin_amd64.tar.gz"
      sha256 "6978f3f2fc7eaa029c38d4d9f7a733636fa353e524f766cb4cf4b906e13225df"
    end
    on_arm do
      url "https://github.com/fmueller/voxclip/releases/download/v#{version}/voxclip_#{version}_darwin_arm64.tar.gz"
      sha256 "411c0df6937a26f5283a8bffab0efdd11059d9035bf614c3d0564a69f355e174"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fmueller/voxclip/releases/download/v#{version}/voxclip_#{version}_linux_amd64.tar.gz"
      sha256 "1e38b8135a7e60d1e0a7b943b621ade1c41633a1daff16ddc01fc96c954fa8ff"
    end
    on_arm do
      url "https://github.com/fmueller/voxclip/releases/download/v#{version}/voxclip_#{version}_linux_arm64.tar.gz"
      sha256 "879e1ba690e2f24caaaa70628ecf3ef1e1076cefed4aefb952ec2be78c1c385c"
    end
  end

  caveats do
    "Run `voxclip setup` after install to download a speech model."
  end

  # No zap stanza required
end
